# Generated by Django 4.2.10 on 2026-02-08 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fazenda", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Talhao",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "cultura",
                    models.CharField(
                        choices=[
                            ("milho", "Milho"),
                            ("soja", "Soja"),
                            ("trigo", "Trigo"),
                            ("arroz", "Arroz"),
                            ("cana_de_acucar", "Cana de Açúcar"),
                            ("cafe", "Café"),
                            ("algodao", "Algodão"),
                            ("feijao", "Feijão"),
                            ("outro", "Outro"),
                        ],
                        default="milho",
                        max_length=20,
                    ),
                ),
                (
                    "area_hectares",
                    models.DecimalField(
                        decimal_places=2, help_text="Área em hectares", max_digits=10
                    ),
                ),
                (
                    "geometria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Polígono em formato GeoJSON com coordenadas [lng, lat]",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("pousio", "Pousio"),
                            ("inativo", "Inativo"),
                        ],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                ("data_plantio", models.DateField(blank=True, null=True)),
                ("data_colheita", models.DateField(blank=True, null=True)),
                (
                    "rendimento_esperado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rendimento esperado em sacas/ha ou toneladas/ha",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "rendimento_real",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rendimento real em sacas/ha ou toneladas/ha",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "fazenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talhoes",
                        to="fazenda.fazenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Talhão",
                "verbose_name_plural": "Talhões",
                "ordering": ["-data_criacao"],
                "indexes": [
                    models.Index(
                        fields=["fazenda", "status"],
                        name="talhoes_tal_fazenda_eadafc_idx",
                    )
                ],
            },
        ),
    ]
