# Generated by Django 4.2.10 on 2026-02-08 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("mensagem", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("info", "Informação"),
                            ("alerta", "Alerta"),
                            ("critico", "Crítico"),
                            ("sucesso", "Sucesso"),
                            ("erro", "Erro"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("clima", "Clima"),
                            ("praga", "Praga"),
                            ("irrigacao", "Irrigação"),
                            ("produtividade", "Produtividade"),
                            ("sistema", "Sistema"),
                            ("financeiro", "Financeiro"),
                            ("manutencao", "Manutenção"),
                            ("vencimento", "Vencimento"),
                        ],
                        default="sistema",
                        max_length=30,
                    ),
                ),
                (
                    "prioridade",
                    models.IntegerField(
                        default=0, help_text="0=normal, 1=alta, 2=urgente"
                    ),
                ),
                ("lida", models.BooleanField(default=False)),
                ("data_leitura", models.DateTimeField(blank=True, null=True)),
                ("arquivada", models.BooleanField(default=False)),
                ("link", models.CharField(blank=True, max_length=500, null=True)),
                ("acao_requerida", models.BooleanField(default=False)),
                ("fazenda_id", models.IntegerField(blank=True, null=True)),
                ("talhao_id", models.IntegerField(blank=True, null=True)),
                ("praga_id", models.IntegerField(blank=True, null=True)),
                ("irrigacao_id", models.IntegerField(blank=True, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["-data_criacao"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "-data_criacao"],
                        name="notificacoe_usuario_1031fd_idx",
                    ),
                    models.Index(
                        fields=["usuario", "lida"],
                        name="notificacoe_usuario_a5894e_idx",
                    ),
                ],
            },
        ),
    ]
