# Generated by Django 4.2.10 on 2026-02-07 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fazenda", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Praga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, default="")),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("baixo", "Baixo"),
                            ("medio", "Médio"),
                            ("alto", "Alto"),
                            ("critico", "Crítico"),
                        ],
                        default="baixo",
                        max_length=20,
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="pragas/"),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pendente", "Pendente"), ("resolvido", "Resolvido")],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "fazenda",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fazenda.fazenda",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
