# Generated by Django 4.2.10 on 2025-01-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosClimaticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('umidade', models.FloatField()),
                ('precipitacao', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
