# Generated by Django 4.2.10 on 2025-02-13 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fazenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosClimaticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('umidade', models.FloatField()),
                ('precipitacao', models.FloatField()),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazenda.fazenda')),
            ],
        ),
    ]
