# Generated by Django 4.2.10 on 2025-02-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0001_initial'),
        ('irrigacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosclimaticos',
            name='fazenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fazenda.fazenda'),
        ),
    ]
