# Generated by Django 4.2.10 on 2025-02-18 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0001_initial'),
        ('irrigacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irrigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=20)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigacoes', to='fazenda.fazenda')),
            ],
        ),
    ]
