# Generated by Django 4.2.10 on 2026-02-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("irrigacao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dadosclimaticos",
            name="e_previsao",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dadosclimaticos",
            name="velocidade_vento",
            field=models.FloatField(default=0),
        ),
    ]
