# Generated by Django 4.2.10 on 2026-01-11 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fazenda", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("zoom", models.IntegerField(default=10)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "fazenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapas",
                        to="fazenda.fazenda",
                    ),
                ),
            ],
        ),
    ]
