# Generated by Django 4.2.10 on 2026-01-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapa",
            name="camadas",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="mapa",
            name="data_atualizacao",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
