# Generated by Django 4.2.10 on 2026-02-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0002_mapa_camadas_mapa_data_atualizacao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mapa",
            options={"ordering": ["-data_criacao"]},
        ),
        migrations.AddField(
            model_name="mapa",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mapa",
            name="filtros",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="mapa",
            name="publico",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mapa",
            name="tipo_mapa",
            field=models.CharField(
                choices=[
                    ("osm", "OpenStreetMap"),
                    ("satellite", "Satélite"),
                    ("terrain", "Terreno"),
                    ("dark", "Modo Escuro"),
                ],
                default="satellite",
                max_length=50,
            ),
        ),
    ]
