# Generated by Django 4.2.10 on 2026-02-08 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("talhoes", "0001_initial"),
        ("fazenda", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DadosProdutividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cultura", models.CharField(max_length=100)),
                (
                    "area_hectares",
                    models.FloatField(default=0, help_text="Área em hectares"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planejado", "Planejado"),
                            ("em_cultivo", "Em Cultivo"),
                            ("colhido", "Colhido"),
                            ("perdido", "Perdido"),
                        ],
                        default="em_cultivo",
                        max_length=20,
                    ),
                ),
                ("data_plantio", models.DateField(blank=True, null=True)),
                ("data_colheita", models.DateField(blank=True, null=True)),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "peso_colhido_kg",
                    models.FloatField(
                        blank=True, help_text="Peso colhido em kg", null=True
                    ),
                ),
                (
                    "rendimento_kg_ha",
                    models.FloatField(
                        blank=True, help_text="Rendimento em kg/hectare", null=True
                    ),
                ),
                (
                    "preco_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "receita_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "custo_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "lucro_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("observacoes", models.TextField(blank=True, default="")),
                (
                    "fazenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtividade_dados",
                        to="fazenda.fazenda",
                    ),
                ),
                (
                    "talhao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtividade_dados",
                        to="talhoes.talhao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dados de Produtividade",
                "ordering": ["-data_colheita", "-data_registro"],
            },
        ),
    ]
